18 add report screenshots
csia-pme/a-guide-to-mlops pull request #19
Opened 2023-03-21 14:57 UTC by leonardcser

Below are the changes mentioned in the issue #18. 

For the custom style for the images (f289bd49bd80f51592339c9af9c89ea57e80c4fe), the value `.2rem` is the same as for the info/warning boxes.

2023-03-22 12:11 UTC, ludelafo requested changes
I would rather use the "official" `assets/images` directory such as on the official Material for MkDocs repository: https://github.com/squidfunk/mkdocs-material/tree/master/docs/assets/images (usage here: https://github.com/squidfunk/mkdocs-material/blob/master/docs/reference/images.md?plain=1#L177-L178) instead of the `media` directory in the `the-guide` directory as we might want to add future images that aren't part of The guide. What do you think?

2023-03-22 12:11 UTC, ludelafo commented on docs/the-guide/media/plots_diff.png
Have you compressed your images with a software such as [Caesium Image Compressor](https://caesium.app/) to save all available space? You can compress the files "losslessly" and still save a few KBs.

2023-03-22 12:17 UTC, leonardcser commented on docs/stylesheets/extra.css
> +}
The difference is very subtle. It slightly rounds the corners of the images inside of `article` tags, so the main content of the docs. This is to keep style consistency with the rounding of info/warning boxes and code blocks.

2023-03-23 09:35 UTC, ludelafo approved these changes
All good for me!

2023-03-23 09:35 UTC, ludelafo commented on docs/stylesheets/extra.css
> +}
Ok! Good point, thank you for the explanation.

2023-03-23 09:38 UTC, merged